//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.ServiceLocal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLocal.IConsultas")]
    public interface IConsultas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/Rastreamento", ReplyAction="http://tempuri.org/IConsultas/RastreamentoResponse")]
        string Rastreamento(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino, int codigoFinanceiro);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/Rastreamento", ReplyAction="http://tempuri.org/IConsultas/RastreamentoResponse")]
        System.IAsyncResult BeginRastreamento(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    int codigoFinanceiro, 
                    System.AsyncCallback callback, 
                    object asyncState);
        
        string EndRastreamento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/RastreamentoComModal", ReplyAction="http://tempuri.org/IConsultas/RastreamentoComModalResponse")]
        string RastreamentoComModal(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    int codigoFinanceiro, 
                    string modal);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/RastreamentoComModal", ReplyAction="http://tempuri.org/IConsultas/RastreamentoComModalResponse")]
        System.IAsyncResult BeginRastreamentoComModal(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    int codigoFinanceiro, 
                    string modal, 
                    System.AsyncCallback callback, 
                    object asyncState);
        
        string EndRastreamentoComModal(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/Embarque", ReplyAction="http://tempuri.org/IConsultas/EmbarqueResponse")]
        string Embarque(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/Embarque", ReplyAction="http://tempuri.org/IConsultas/EmbarqueResponse")]
        System.IAsyncResult BeginEmbarque(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    System.AsyncCallback callback, 
                    object asyncState);
        
        string EndEmbarque(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/EmbarqueComModal", ReplyAction="http://tempuri.org/IConsultas/EmbarqueComModalResponse")]
        string EmbarqueComModal(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino, string modal);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/EmbarqueComModal", ReplyAction="http://tempuri.org/IConsultas/EmbarqueComModalResponse")]
        System.IAsyncResult BeginEmbarqueComModal(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    string modal, 
                    System.AsyncCallback callback, 
                    object asyncState);
        
        string EndEmbarqueComModal(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/DetalheEmbarque", ReplyAction="http://tempuri.org/IConsultas/DetalheEmbarqueResponse")]
        string DetalheEmbarque(string login, string senha, int idMovimento);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/DetalheEmbarque", ReplyAction="http://tempuri.org/IConsultas/DetalheEmbarqueResponse")]
        System.IAsyncResult BeginDetalheEmbarque(string login, string senha, int idMovimento, System.AsyncCallback callback, object asyncState);
        
        string EndDetalheEmbarque(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/OcorrenciasNovo", ReplyAction="http://tempuri.org/IConsultas/OcorrenciasNovoResponse")]
        string OcorrenciasNovo(string codigoMovimento);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/OcorrenciasNovo", ReplyAction="http://tempuri.org/IConsultas/OcorrenciasNovoResponse")]
        System.IAsyncResult BeginOcorrenciasNovo(string codigoMovimento, System.AsyncCallback callback, object asyncState);
        
        string EndOcorrenciasNovo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/RetornarLoginCliente", ReplyAction="http://tempuri.org/IConsultas/RetornarLoginClienteResponse")]
        string RetornarLoginCliente(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/RetornarLoginCliente", ReplyAction="http://tempuri.org/IConsultas/RetornarLoginClienteResponse")]
        System.IAsyncResult BeginRetornarLoginCliente(string login, string senha, System.AsyncCallback callback, object asyncState);
        
        string EndRetornarLoginCliente(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/ListarCentroCusto", ReplyAction="http://tempuri.org/IConsultas/ListarCentroCustoResponse")]
        string ListarCentroCusto(string login, string senha, int codigoRemetente);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/ListarCentroCusto", ReplyAction="http://tempuri.org/IConsultas/ListarCentroCustoResponse")]
        System.IAsyncResult BeginListarCentroCusto(string login, string senha, int codigoRemetente, System.AsyncCallback callback, object asyncState);
        
        string EndListarCentroCusto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/ListarCidade", ReplyAction="http://tempuri.org/IConsultas/ListarCidadeResponse")]
        string ListarCidade(string login, string senha, string estado, string cidade);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/ListarCidade", ReplyAction="http://tempuri.org/IConsultas/ListarCidadeResponse")]
        System.IAsyncResult BeginListarCidade(string login, string senha, string estado, string cidade, System.AsyncCallback callback, object asyncState);
        
        string EndListarCidade(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/ListarPessoa", ReplyAction="http://tempuri.org/IConsultas/ListarPessoaResponse")]
        string ListarPessoa(string login, string senha, bool empresa, string cgcCPF, string nome, int codigoPessoa);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/ListarPessoa", ReplyAction="http://tempuri.org/IConsultas/ListarPessoaResponse")]
        System.IAsyncResult BeginListarPessoa(string login, string senha, bool empresa, string cgcCPF, string nome, int codigoPessoa, System.AsyncCallback callback, object asyncState);
        
        string EndListarPessoa(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultas/ConsultarFinanceiro", ReplyAction="http://tempuri.org/IConsultas/ConsultarFinanceiroResponse")]
        string ConsultarFinanceiro(string login, string senha, string tipoDocumento, string numeroDocumento, string dataVencimentoInicial, string dataVencimentoFinal, string dataEmissaoInicial, string dataEmissaoFinal, int codigoEmpresaEmissora);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsultas/ConsultarFinanceiro", ReplyAction="http://tempuri.org/IConsultas/ConsultarFinanceiroResponse")]
        System.IAsyncResult BeginConsultarFinanceiro(string login, string senha, string tipoDocumento, string numeroDocumento, string dataVencimentoInicial, string dataVencimentoFinal, string dataEmissaoInicial, string dataEmissaoFinal, int codigoEmpresaEmissora, System.AsyncCallback callback, object asyncState);
        
        string EndConsultarFinanceiro(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultasChannel : Teste.ServiceLocal.IConsultas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RastreamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RastreamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RastreamentoComModalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RastreamentoComModalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmbarqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EmbarqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmbarqueComModalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EmbarqueComModalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DetalheEmbarqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DetalheEmbarqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OcorrenciasNovoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public OcorrenciasNovoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetornarLoginClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetornarLoginClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarCentroCustoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarCentroCustoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarCidadeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarCidadeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarPessoaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarPessoaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarFinanceiroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsultarFinanceiroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultasClient : System.ServiceModel.ClientBase<Teste.ServiceLocal.IConsultas>, Teste.ServiceLocal.IConsultas {
        
        private BeginOperationDelegate onBeginRastreamentoDelegate;
        
        private EndOperationDelegate onEndRastreamentoDelegate;
        
        private System.Threading.SendOrPostCallback onRastreamentoCompletedDelegate;
        
        private BeginOperationDelegate onBeginRastreamentoComModalDelegate;
        
        private EndOperationDelegate onEndRastreamentoComModalDelegate;
        
        private System.Threading.SendOrPostCallback onRastreamentoComModalCompletedDelegate;
        
        private BeginOperationDelegate onBeginEmbarqueDelegate;
        
        private EndOperationDelegate onEndEmbarqueDelegate;
        
        private System.Threading.SendOrPostCallback onEmbarqueCompletedDelegate;
        
        private BeginOperationDelegate onBeginEmbarqueComModalDelegate;
        
        private EndOperationDelegate onEndEmbarqueComModalDelegate;
        
        private System.Threading.SendOrPostCallback onEmbarqueComModalCompletedDelegate;
        
        private BeginOperationDelegate onBeginDetalheEmbarqueDelegate;
        
        private EndOperationDelegate onEndDetalheEmbarqueDelegate;
        
        private System.Threading.SendOrPostCallback onDetalheEmbarqueCompletedDelegate;
        
        private BeginOperationDelegate onBeginOcorrenciasNovoDelegate;
        
        private EndOperationDelegate onEndOcorrenciasNovoDelegate;
        
        private System.Threading.SendOrPostCallback onOcorrenciasNovoCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetornarLoginClienteDelegate;
        
        private EndOperationDelegate onEndRetornarLoginClienteDelegate;
        
        private System.Threading.SendOrPostCallback onRetornarLoginClienteCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarCentroCustoDelegate;
        
        private EndOperationDelegate onEndListarCentroCustoDelegate;
        
        private System.Threading.SendOrPostCallback onListarCentroCustoCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarCidadeDelegate;
        
        private EndOperationDelegate onEndListarCidadeDelegate;
        
        private System.Threading.SendOrPostCallback onListarCidadeCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarPessoaDelegate;
        
        private EndOperationDelegate onEndListarPessoaDelegate;
        
        private System.Threading.SendOrPostCallback onListarPessoaCompletedDelegate;
        
        private BeginOperationDelegate onBeginConsultarFinanceiroDelegate;
        
        private EndOperationDelegate onEndConsultarFinanceiroDelegate;
        
        private System.Threading.SendOrPostCallback onConsultarFinanceiroCompletedDelegate;
        
        public ConsultasClient() {
        }
        
        public ConsultasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<RastreamentoCompletedEventArgs> RastreamentoCompleted;
        
        public event System.EventHandler<RastreamentoComModalCompletedEventArgs> RastreamentoComModalCompleted;
        
        public event System.EventHandler<EmbarqueCompletedEventArgs> EmbarqueCompleted;
        
        public event System.EventHandler<EmbarqueComModalCompletedEventArgs> EmbarqueComModalCompleted;
        
        public event System.EventHandler<DetalheEmbarqueCompletedEventArgs> DetalheEmbarqueCompleted;
        
        public event System.EventHandler<OcorrenciasNovoCompletedEventArgs> OcorrenciasNovoCompleted;
        
        public event System.EventHandler<RetornarLoginClienteCompletedEventArgs> RetornarLoginClienteCompleted;
        
        public event System.EventHandler<ListarCentroCustoCompletedEventArgs> ListarCentroCustoCompleted;
        
        public event System.EventHandler<ListarCidadeCompletedEventArgs> ListarCidadeCompleted;
        
        public event System.EventHandler<ListarPessoaCompletedEventArgs> ListarPessoaCompleted;
        
        public event System.EventHandler<ConsultarFinanceiroCompletedEventArgs> ConsultarFinanceiroCompleted;
        
        public string Rastreamento(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino, int codigoFinanceiro) {
            return base.Channel.Rastreamento(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, codigoFinanceiro);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRastreamento(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    int codigoFinanceiro, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return base.Channel.BeginRastreamento(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, codigoFinanceiro, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndRastreamento(System.IAsyncResult result) {
            return base.Channel.EndRastreamento(result);
        }
        
        private System.IAsyncResult OnBeginRastreamento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            string dataInicial = ((string)(inValues[2]));
            string dataFinal = ((string)(inValues[3]));
            int codigoRemetente = ((int)(inValues[4]));
            int codigoDestinatario = ((int)(inValues[5]));
            string entregue = ((string)(inValues[6]));
            string numeroNota = ((string)(inValues[7]));
            string numeroConhecimento = ((string)(inValues[8]));
            int codigoCentroCusto = ((int)(inValues[9]));
            string ufOrigem = ((string)(inValues[10]));
            int cidadeOrigem = ((int)(inValues[11]));
            string ufDestino = ((string)(inValues[12]));
            int cidadeDestino = ((int)(inValues[13]));
            int codigoFinanceiro = ((int)(inValues[14]));
            return this.BeginRastreamento(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, codigoFinanceiro, callback, asyncState);
        }
        
        private object[] OnEndRastreamento(System.IAsyncResult result) {
            string retVal = this.EndRastreamento(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRastreamentoCompleted(object state) {
            if ((this.RastreamentoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RastreamentoCompleted(this, new RastreamentoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RastreamentoAsync(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino, int codigoFinanceiro) {
            this.RastreamentoAsync(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, codigoFinanceiro, null);
        }
        
        public void RastreamentoAsync(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    int codigoFinanceiro, 
                    object userState) {
            if ((this.onBeginRastreamentoDelegate == null)) {
                this.onBeginRastreamentoDelegate = new BeginOperationDelegate(this.OnBeginRastreamento);
            }
            if ((this.onEndRastreamentoDelegate == null)) {
                this.onEndRastreamentoDelegate = new EndOperationDelegate(this.OnEndRastreamento);
            }
            if ((this.onRastreamentoCompletedDelegate == null)) {
                this.onRastreamentoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRastreamentoCompleted);
            }
            base.InvokeAsync(this.onBeginRastreamentoDelegate, new object[] {
                        login,
                        senha,
                        dataInicial,
                        dataFinal,
                        codigoRemetente,
                        codigoDestinatario,
                        entregue,
                        numeroNota,
                        numeroConhecimento,
                        codigoCentroCusto,
                        ufOrigem,
                        cidadeOrigem,
                        ufDestino,
                        cidadeDestino,
                        codigoFinanceiro}, this.onEndRastreamentoDelegate, this.onRastreamentoCompletedDelegate, userState);
        }
        
        public string RastreamentoComModal(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    int codigoFinanceiro, 
                    string modal) {
            return base.Channel.RastreamentoComModal(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, codigoFinanceiro, modal);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRastreamentoComModal(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    int codigoFinanceiro, 
                    string modal, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return base.Channel.BeginRastreamentoComModal(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, codigoFinanceiro, modal, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndRastreamentoComModal(System.IAsyncResult result) {
            return base.Channel.EndRastreamentoComModal(result);
        }
        
        private System.IAsyncResult OnBeginRastreamentoComModal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            string dataInicial = ((string)(inValues[2]));
            string dataFinal = ((string)(inValues[3]));
            int codigoRemetente = ((int)(inValues[4]));
            int codigoDestinatario = ((int)(inValues[5]));
            string entregue = ((string)(inValues[6]));
            string numeroNota = ((string)(inValues[7]));
            string numeroConhecimento = ((string)(inValues[8]));
            int codigoCentroCusto = ((int)(inValues[9]));
            string ufOrigem = ((string)(inValues[10]));
            int cidadeOrigem = ((int)(inValues[11]));
            string ufDestino = ((string)(inValues[12]));
            int cidadeDestino = ((int)(inValues[13]));
            int codigoFinanceiro = ((int)(inValues[14]));
            string modal = ((string)(inValues[15]));
            return this.BeginRastreamentoComModal(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, codigoFinanceiro, modal, callback, asyncState);
        }
        
        private object[] OnEndRastreamentoComModal(System.IAsyncResult result) {
            string retVal = this.EndRastreamentoComModal(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRastreamentoComModalCompleted(object state) {
            if ((this.RastreamentoComModalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RastreamentoComModalCompleted(this, new RastreamentoComModalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RastreamentoComModalAsync(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    int codigoFinanceiro, 
                    string modal) {
            this.RastreamentoComModalAsync(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, codigoFinanceiro, modal, null);
        }
        
        public void RastreamentoComModalAsync(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    int codigoFinanceiro, 
                    string modal, 
                    object userState) {
            if ((this.onBeginRastreamentoComModalDelegate == null)) {
                this.onBeginRastreamentoComModalDelegate = new BeginOperationDelegate(this.OnBeginRastreamentoComModal);
            }
            if ((this.onEndRastreamentoComModalDelegate == null)) {
                this.onEndRastreamentoComModalDelegate = new EndOperationDelegate(this.OnEndRastreamentoComModal);
            }
            if ((this.onRastreamentoComModalCompletedDelegate == null)) {
                this.onRastreamentoComModalCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRastreamentoComModalCompleted);
            }
            base.InvokeAsync(this.onBeginRastreamentoComModalDelegate, new object[] {
                        login,
                        senha,
                        dataInicial,
                        dataFinal,
                        codigoRemetente,
                        codigoDestinatario,
                        entregue,
                        numeroNota,
                        numeroConhecimento,
                        codigoCentroCusto,
                        ufOrigem,
                        cidadeOrigem,
                        ufDestino,
                        cidadeDestino,
                        codigoFinanceiro,
                        modal}, this.onEndRastreamentoComModalDelegate, this.onRastreamentoComModalCompletedDelegate, userState);
        }
        
        public string Embarque(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino) {
            return base.Channel.Embarque(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEmbarque(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return base.Channel.BeginEmbarque(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndEmbarque(System.IAsyncResult result) {
            return base.Channel.EndEmbarque(result);
        }
        
        private System.IAsyncResult OnBeginEmbarque(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            string dataInicial = ((string)(inValues[2]));
            string dataFinal = ((string)(inValues[3]));
            int codigoRemetente = ((int)(inValues[4]));
            int codigoDestinatario = ((int)(inValues[5]));
            string entregue = ((string)(inValues[6]));
            string numeroNota = ((string)(inValues[7]));
            string numeroConhecimento = ((string)(inValues[8]));
            int codigoCentroCusto = ((int)(inValues[9]));
            string ufOrigem = ((string)(inValues[10]));
            int cidadeOrigem = ((int)(inValues[11]));
            string ufDestino = ((string)(inValues[12]));
            int cidadeDestino = ((int)(inValues[13]));
            return this.BeginEmbarque(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, callback, asyncState);
        }
        
        private object[] OnEndEmbarque(System.IAsyncResult result) {
            string retVal = this.EndEmbarque(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEmbarqueCompleted(object state) {
            if ((this.EmbarqueCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EmbarqueCompleted(this, new EmbarqueCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EmbarqueAsync(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino) {
            this.EmbarqueAsync(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, null);
        }
        
        public void EmbarqueAsync(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino, object userState) {
            if ((this.onBeginEmbarqueDelegate == null)) {
                this.onBeginEmbarqueDelegate = new BeginOperationDelegate(this.OnBeginEmbarque);
            }
            if ((this.onEndEmbarqueDelegate == null)) {
                this.onEndEmbarqueDelegate = new EndOperationDelegate(this.OnEndEmbarque);
            }
            if ((this.onEmbarqueCompletedDelegate == null)) {
                this.onEmbarqueCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEmbarqueCompleted);
            }
            base.InvokeAsync(this.onBeginEmbarqueDelegate, new object[] {
                        login,
                        senha,
                        dataInicial,
                        dataFinal,
                        codigoRemetente,
                        codigoDestinatario,
                        entregue,
                        numeroNota,
                        numeroConhecimento,
                        codigoCentroCusto,
                        ufOrigem,
                        cidadeOrigem,
                        ufDestino,
                        cidadeDestino}, this.onEndEmbarqueDelegate, this.onEmbarqueCompletedDelegate, userState);
        }
        
        public string EmbarqueComModal(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino, string modal) {
            return base.Channel.EmbarqueComModal(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, modal);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEmbarqueComModal(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    string modal, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return base.Channel.BeginEmbarqueComModal(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, modal, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndEmbarqueComModal(System.IAsyncResult result) {
            return base.Channel.EndEmbarqueComModal(result);
        }
        
        private System.IAsyncResult OnBeginEmbarqueComModal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            string dataInicial = ((string)(inValues[2]));
            string dataFinal = ((string)(inValues[3]));
            int codigoRemetente = ((int)(inValues[4]));
            int codigoDestinatario = ((int)(inValues[5]));
            string entregue = ((string)(inValues[6]));
            string numeroNota = ((string)(inValues[7]));
            string numeroConhecimento = ((string)(inValues[8]));
            int codigoCentroCusto = ((int)(inValues[9]));
            string ufOrigem = ((string)(inValues[10]));
            int cidadeOrigem = ((int)(inValues[11]));
            string ufDestino = ((string)(inValues[12]));
            int cidadeDestino = ((int)(inValues[13]));
            string modal = ((string)(inValues[14]));
            return this.BeginEmbarqueComModal(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, modal, callback, asyncState);
        }
        
        private object[] OnEndEmbarqueComModal(System.IAsyncResult result) {
            string retVal = this.EndEmbarqueComModal(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEmbarqueComModalCompleted(object state) {
            if ((this.EmbarqueComModalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EmbarqueComModalCompleted(this, new EmbarqueComModalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EmbarqueComModalAsync(string login, string senha, string dataInicial, string dataFinal, int codigoRemetente, int codigoDestinatario, string entregue, string numeroNota, string numeroConhecimento, int codigoCentroCusto, string ufOrigem, int cidadeOrigem, string ufDestino, int cidadeDestino, string modal) {
            this.EmbarqueComModalAsync(login, senha, dataInicial, dataFinal, codigoRemetente, codigoDestinatario, entregue, numeroNota, numeroConhecimento, codigoCentroCusto, ufOrigem, cidadeOrigem, ufDestino, cidadeDestino, modal, null);
        }
        
        public void EmbarqueComModalAsync(
                    string login, 
                    string senha, 
                    string dataInicial, 
                    string dataFinal, 
                    int codigoRemetente, 
                    int codigoDestinatario, 
                    string entregue, 
                    string numeroNota, 
                    string numeroConhecimento, 
                    int codigoCentroCusto, 
                    string ufOrigem, 
                    int cidadeOrigem, 
                    string ufDestino, 
                    int cidadeDestino, 
                    string modal, 
                    object userState) {
            if ((this.onBeginEmbarqueComModalDelegate == null)) {
                this.onBeginEmbarqueComModalDelegate = new BeginOperationDelegate(this.OnBeginEmbarqueComModal);
            }
            if ((this.onEndEmbarqueComModalDelegate == null)) {
                this.onEndEmbarqueComModalDelegate = new EndOperationDelegate(this.OnEndEmbarqueComModal);
            }
            if ((this.onEmbarqueComModalCompletedDelegate == null)) {
                this.onEmbarqueComModalCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEmbarqueComModalCompleted);
            }
            base.InvokeAsync(this.onBeginEmbarqueComModalDelegate, new object[] {
                        login,
                        senha,
                        dataInicial,
                        dataFinal,
                        codigoRemetente,
                        codigoDestinatario,
                        entregue,
                        numeroNota,
                        numeroConhecimento,
                        codigoCentroCusto,
                        ufOrigem,
                        cidadeOrigem,
                        ufDestino,
                        cidadeDestino,
                        modal}, this.onEndEmbarqueComModalDelegate, this.onEmbarqueComModalCompletedDelegate, userState);
        }
        
        public string DetalheEmbarque(string login, string senha, int idMovimento) {
            return base.Channel.DetalheEmbarque(login, senha, idMovimento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDetalheEmbarque(string login, string senha, int idMovimento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDetalheEmbarque(login, senha, idMovimento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndDetalheEmbarque(System.IAsyncResult result) {
            return base.Channel.EndDetalheEmbarque(result);
        }
        
        private System.IAsyncResult OnBeginDetalheEmbarque(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            int idMovimento = ((int)(inValues[2]));
            return this.BeginDetalheEmbarque(login, senha, idMovimento, callback, asyncState);
        }
        
        private object[] OnEndDetalheEmbarque(System.IAsyncResult result) {
            string retVal = this.EndDetalheEmbarque(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDetalheEmbarqueCompleted(object state) {
            if ((this.DetalheEmbarqueCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DetalheEmbarqueCompleted(this, new DetalheEmbarqueCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DetalheEmbarqueAsync(string login, string senha, int idMovimento) {
            this.DetalheEmbarqueAsync(login, senha, idMovimento, null);
        }
        
        public void DetalheEmbarqueAsync(string login, string senha, int idMovimento, object userState) {
            if ((this.onBeginDetalheEmbarqueDelegate == null)) {
                this.onBeginDetalheEmbarqueDelegate = new BeginOperationDelegate(this.OnBeginDetalheEmbarque);
            }
            if ((this.onEndDetalheEmbarqueDelegate == null)) {
                this.onEndDetalheEmbarqueDelegate = new EndOperationDelegate(this.OnEndDetalheEmbarque);
            }
            if ((this.onDetalheEmbarqueCompletedDelegate == null)) {
                this.onDetalheEmbarqueCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDetalheEmbarqueCompleted);
            }
            base.InvokeAsync(this.onBeginDetalheEmbarqueDelegate, new object[] {
                        login,
                        senha,
                        idMovimento}, this.onEndDetalheEmbarqueDelegate, this.onDetalheEmbarqueCompletedDelegate, userState);
        }
        
        public string OcorrenciasNovo(string codigoMovimento) {
            return base.Channel.OcorrenciasNovo(codigoMovimento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginOcorrenciasNovo(string codigoMovimento, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginOcorrenciasNovo(codigoMovimento, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndOcorrenciasNovo(System.IAsyncResult result) {
            return base.Channel.EndOcorrenciasNovo(result);
        }
        
        private System.IAsyncResult OnBeginOcorrenciasNovo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string codigoMovimento = ((string)(inValues[0]));
            return this.BeginOcorrenciasNovo(codigoMovimento, callback, asyncState);
        }
        
        private object[] OnEndOcorrenciasNovo(System.IAsyncResult result) {
            string retVal = this.EndOcorrenciasNovo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnOcorrenciasNovoCompleted(object state) {
            if ((this.OcorrenciasNovoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OcorrenciasNovoCompleted(this, new OcorrenciasNovoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OcorrenciasNovoAsync(string codigoMovimento) {
            this.OcorrenciasNovoAsync(codigoMovimento, null);
        }
        
        public void OcorrenciasNovoAsync(string codigoMovimento, object userState) {
            if ((this.onBeginOcorrenciasNovoDelegate == null)) {
                this.onBeginOcorrenciasNovoDelegate = new BeginOperationDelegate(this.OnBeginOcorrenciasNovo);
            }
            if ((this.onEndOcorrenciasNovoDelegate == null)) {
                this.onEndOcorrenciasNovoDelegate = new EndOperationDelegate(this.OnEndOcorrenciasNovo);
            }
            if ((this.onOcorrenciasNovoCompletedDelegate == null)) {
                this.onOcorrenciasNovoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOcorrenciasNovoCompleted);
            }
            base.InvokeAsync(this.onBeginOcorrenciasNovoDelegate, new object[] {
                        codigoMovimento}, this.onEndOcorrenciasNovoDelegate, this.onOcorrenciasNovoCompletedDelegate, userState);
        }
        
        public string RetornarLoginCliente(string login, string senha) {
            return base.Channel.RetornarLoginCliente(login, senha);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRetornarLoginCliente(string login, string senha, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetornarLoginCliente(login, senha, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndRetornarLoginCliente(System.IAsyncResult result) {
            return base.Channel.EndRetornarLoginCliente(result);
        }
        
        private System.IAsyncResult OnBeginRetornarLoginCliente(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            return this.BeginRetornarLoginCliente(login, senha, callback, asyncState);
        }
        
        private object[] OnEndRetornarLoginCliente(System.IAsyncResult result) {
            string retVal = this.EndRetornarLoginCliente(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetornarLoginClienteCompleted(object state) {
            if ((this.RetornarLoginClienteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetornarLoginClienteCompleted(this, new RetornarLoginClienteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetornarLoginClienteAsync(string login, string senha) {
            this.RetornarLoginClienteAsync(login, senha, null);
        }
        
        public void RetornarLoginClienteAsync(string login, string senha, object userState) {
            if ((this.onBeginRetornarLoginClienteDelegate == null)) {
                this.onBeginRetornarLoginClienteDelegate = new BeginOperationDelegate(this.OnBeginRetornarLoginCliente);
            }
            if ((this.onEndRetornarLoginClienteDelegate == null)) {
                this.onEndRetornarLoginClienteDelegate = new EndOperationDelegate(this.OnEndRetornarLoginCliente);
            }
            if ((this.onRetornarLoginClienteCompletedDelegate == null)) {
                this.onRetornarLoginClienteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetornarLoginClienteCompleted);
            }
            base.InvokeAsync(this.onBeginRetornarLoginClienteDelegate, new object[] {
                        login,
                        senha}, this.onEndRetornarLoginClienteDelegate, this.onRetornarLoginClienteCompletedDelegate, userState);
        }
        
        public string ListarCentroCusto(string login, string senha, int codigoRemetente) {
            return base.Channel.ListarCentroCusto(login, senha, codigoRemetente);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListarCentroCusto(string login, string senha, int codigoRemetente, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarCentroCusto(login, senha, codigoRemetente, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndListarCentroCusto(System.IAsyncResult result) {
            return base.Channel.EndListarCentroCusto(result);
        }
        
        private System.IAsyncResult OnBeginListarCentroCusto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            int codigoRemetente = ((int)(inValues[2]));
            return this.BeginListarCentroCusto(login, senha, codigoRemetente, callback, asyncState);
        }
        
        private object[] OnEndListarCentroCusto(System.IAsyncResult result) {
            string retVal = this.EndListarCentroCusto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarCentroCustoCompleted(object state) {
            if ((this.ListarCentroCustoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarCentroCustoCompleted(this, new ListarCentroCustoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarCentroCustoAsync(string login, string senha, int codigoRemetente) {
            this.ListarCentroCustoAsync(login, senha, codigoRemetente, null);
        }
        
        public void ListarCentroCustoAsync(string login, string senha, int codigoRemetente, object userState) {
            if ((this.onBeginListarCentroCustoDelegate == null)) {
                this.onBeginListarCentroCustoDelegate = new BeginOperationDelegate(this.OnBeginListarCentroCusto);
            }
            if ((this.onEndListarCentroCustoDelegate == null)) {
                this.onEndListarCentroCustoDelegate = new EndOperationDelegate(this.OnEndListarCentroCusto);
            }
            if ((this.onListarCentroCustoCompletedDelegate == null)) {
                this.onListarCentroCustoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarCentroCustoCompleted);
            }
            base.InvokeAsync(this.onBeginListarCentroCustoDelegate, new object[] {
                        login,
                        senha,
                        codigoRemetente}, this.onEndListarCentroCustoDelegate, this.onListarCentroCustoCompletedDelegate, userState);
        }
        
        public string ListarCidade(string login, string senha, string estado, string cidade) {
            return base.Channel.ListarCidade(login, senha, estado, cidade);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListarCidade(string login, string senha, string estado, string cidade, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarCidade(login, senha, estado, cidade, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndListarCidade(System.IAsyncResult result) {
            return base.Channel.EndListarCidade(result);
        }
        
        private System.IAsyncResult OnBeginListarCidade(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            string estado = ((string)(inValues[2]));
            string cidade = ((string)(inValues[3]));
            return this.BeginListarCidade(login, senha, estado, cidade, callback, asyncState);
        }
        
        private object[] OnEndListarCidade(System.IAsyncResult result) {
            string retVal = this.EndListarCidade(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarCidadeCompleted(object state) {
            if ((this.ListarCidadeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarCidadeCompleted(this, new ListarCidadeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarCidadeAsync(string login, string senha, string estado, string cidade) {
            this.ListarCidadeAsync(login, senha, estado, cidade, null);
        }
        
        public void ListarCidadeAsync(string login, string senha, string estado, string cidade, object userState) {
            if ((this.onBeginListarCidadeDelegate == null)) {
                this.onBeginListarCidadeDelegate = new BeginOperationDelegate(this.OnBeginListarCidade);
            }
            if ((this.onEndListarCidadeDelegate == null)) {
                this.onEndListarCidadeDelegate = new EndOperationDelegate(this.OnEndListarCidade);
            }
            if ((this.onListarCidadeCompletedDelegate == null)) {
                this.onListarCidadeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarCidadeCompleted);
            }
            base.InvokeAsync(this.onBeginListarCidadeDelegate, new object[] {
                        login,
                        senha,
                        estado,
                        cidade}, this.onEndListarCidadeDelegate, this.onListarCidadeCompletedDelegate, userState);
        }
        
        public string ListarPessoa(string login, string senha, bool empresa, string cgcCPF, string nome, int codigoPessoa) {
            return base.Channel.ListarPessoa(login, senha, empresa, cgcCPF, nome, codigoPessoa);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListarPessoa(string login, string senha, bool empresa, string cgcCPF, string nome, int codigoPessoa, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarPessoa(login, senha, empresa, cgcCPF, nome, codigoPessoa, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndListarPessoa(System.IAsyncResult result) {
            return base.Channel.EndListarPessoa(result);
        }
        
        private System.IAsyncResult OnBeginListarPessoa(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            bool empresa = ((bool)(inValues[2]));
            string cgcCPF = ((string)(inValues[3]));
            string nome = ((string)(inValues[4]));
            int codigoPessoa = ((int)(inValues[5]));
            return this.BeginListarPessoa(login, senha, empresa, cgcCPF, nome, codigoPessoa, callback, asyncState);
        }
        
        private object[] OnEndListarPessoa(System.IAsyncResult result) {
            string retVal = this.EndListarPessoa(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarPessoaCompleted(object state) {
            if ((this.ListarPessoaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarPessoaCompleted(this, new ListarPessoaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarPessoaAsync(string login, string senha, bool empresa, string cgcCPF, string nome, int codigoPessoa) {
            this.ListarPessoaAsync(login, senha, empresa, cgcCPF, nome, codigoPessoa, null);
        }
        
        public void ListarPessoaAsync(string login, string senha, bool empresa, string cgcCPF, string nome, int codigoPessoa, object userState) {
            if ((this.onBeginListarPessoaDelegate == null)) {
                this.onBeginListarPessoaDelegate = new BeginOperationDelegate(this.OnBeginListarPessoa);
            }
            if ((this.onEndListarPessoaDelegate == null)) {
                this.onEndListarPessoaDelegate = new EndOperationDelegate(this.OnEndListarPessoa);
            }
            if ((this.onListarPessoaCompletedDelegate == null)) {
                this.onListarPessoaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarPessoaCompleted);
            }
            base.InvokeAsync(this.onBeginListarPessoaDelegate, new object[] {
                        login,
                        senha,
                        empresa,
                        cgcCPF,
                        nome,
                        codigoPessoa}, this.onEndListarPessoaDelegate, this.onListarPessoaCompletedDelegate, userState);
        }
        
        public string ConsultarFinanceiro(string login, string senha, string tipoDocumento, string numeroDocumento, string dataVencimentoInicial, string dataVencimentoFinal, string dataEmissaoInicial, string dataEmissaoFinal, int codigoEmpresaEmissora) {
            return base.Channel.ConsultarFinanceiro(login, senha, tipoDocumento, numeroDocumento, dataVencimentoInicial, dataVencimentoFinal, dataEmissaoInicial, dataEmissaoFinal, codigoEmpresaEmissora);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConsultarFinanceiro(string login, string senha, string tipoDocumento, string numeroDocumento, string dataVencimentoInicial, string dataVencimentoFinal, string dataEmissaoInicial, string dataEmissaoFinal, int codigoEmpresaEmissora, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsultarFinanceiro(login, senha, tipoDocumento, numeroDocumento, dataVencimentoInicial, dataVencimentoFinal, dataEmissaoInicial, dataEmissaoFinal, codigoEmpresaEmissora, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndConsultarFinanceiro(System.IAsyncResult result) {
            return base.Channel.EndConsultarFinanceiro(result);
        }
        
        private System.IAsyncResult OnBeginConsultarFinanceiro(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            string tipoDocumento = ((string)(inValues[2]));
            string numeroDocumento = ((string)(inValues[3]));
            string dataVencimentoInicial = ((string)(inValues[4]));
            string dataVencimentoFinal = ((string)(inValues[5]));
            string dataEmissaoInicial = ((string)(inValues[6]));
            string dataEmissaoFinal = ((string)(inValues[7]));
            int codigoEmpresaEmissora = ((int)(inValues[8]));
            return this.BeginConsultarFinanceiro(login, senha, tipoDocumento, numeroDocumento, dataVencimentoInicial, dataVencimentoFinal, dataEmissaoInicial, dataEmissaoFinal, codigoEmpresaEmissora, callback, asyncState);
        }
        
        private object[] OnEndConsultarFinanceiro(System.IAsyncResult result) {
            string retVal = this.EndConsultarFinanceiro(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsultarFinanceiroCompleted(object state) {
            if ((this.ConsultarFinanceiroCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsultarFinanceiroCompleted(this, new ConsultarFinanceiroCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsultarFinanceiroAsync(string login, string senha, string tipoDocumento, string numeroDocumento, string dataVencimentoInicial, string dataVencimentoFinal, string dataEmissaoInicial, string dataEmissaoFinal, int codigoEmpresaEmissora) {
            this.ConsultarFinanceiroAsync(login, senha, tipoDocumento, numeroDocumento, dataVencimentoInicial, dataVencimentoFinal, dataEmissaoInicial, dataEmissaoFinal, codigoEmpresaEmissora, null);
        }
        
        public void ConsultarFinanceiroAsync(string login, string senha, string tipoDocumento, string numeroDocumento, string dataVencimentoInicial, string dataVencimentoFinal, string dataEmissaoInicial, string dataEmissaoFinal, int codigoEmpresaEmissora, object userState) {
            if ((this.onBeginConsultarFinanceiroDelegate == null)) {
                this.onBeginConsultarFinanceiroDelegate = new BeginOperationDelegate(this.OnBeginConsultarFinanceiro);
            }
            if ((this.onEndConsultarFinanceiroDelegate == null)) {
                this.onEndConsultarFinanceiroDelegate = new EndOperationDelegate(this.OnEndConsultarFinanceiro);
            }
            if ((this.onConsultarFinanceiroCompletedDelegate == null)) {
                this.onConsultarFinanceiroCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsultarFinanceiroCompleted);
            }
            base.InvokeAsync(this.onBeginConsultarFinanceiroDelegate, new object[] {
                        login,
                        senha,
                        tipoDocumento,
                        numeroDocumento,
                        dataVencimentoInicial,
                        dataVencimentoFinal,
                        dataEmissaoInicial,
                        dataEmissaoFinal,
                        codigoEmpresaEmissora}, this.onEndConsultarFinanceiroDelegate, this.onConsultarFinanceiroCompletedDelegate, userState);
        }
    }
}
